### PR TITLE
Pull Request for #19

### PR DESCRIPTION
**Pull request by mlazaric**
I'll open this right now so as I commit you can say what you don't like and I can change it. But if you would prefer not to have this open, feel free to close it for now and I'll open it when I'm done. 

From #19:
- [x] Delete test.js
- [x] lib/index.js shouldn't be committed as to make PRs cleaner.
- [x] Abstract the keymap to another file
- [x] Fix formatting
- [x] Promisify everything
- [x] Fix tests
- [ ] Update readme
- [x] Generate docco documentation.
- [ ] Possible helper methods to validate caches. (If-Modified-Since...)

### CODE REVIEW

**Comment by enyo** [comment]
Hey @logomaster256 

Thanks for your work! Very cool stuff.

1. What do you mean exactly?
2. Ok.
3. Sorry again, could you elaborate?
4. [“filename” can be written as one word or two](http://en.wikipedia.org/wiki/Filename). Personally I prefer “filename”
5. TheTVDBs inconsistency has been bugging me a lot as well. Yes.. it will require special keymaps.

**Comment by logomaster256** [comment]
(1.) [This](https://github.com/enyo/node-tvdb/pull/21/files#diff-2fbc5085a7bbe6fb696a1a3b75a6f420R348) and [this](https://github.com/enyo/node-tvdb/pull/21/files#diff-f3cecf3ba68090c749514a92c32b95abR86) are *almost* obsolete. (Only Series needs to be formatted) 
(3.) [These](https://github.com/enyo/node-tvdb/pull/21/files#diff-2fbc5085a7bbe6fb696a1a3b75a6f420R374), for the most part, aren't needed, unless we want to do something special, like with the dates. But then again since we need them for FirstAired, maybe we should keep them for everything because consistency.

**Comment by enyo** [comment]
Hey, I was just asked by https://github.com/edwellbrook/node-tvdb if we are still developing this library. I said that I currently don't have the time, but that you guys might still work on it.
If you also dropped the project, we could give the npm name `tvdb` to the other library?

**Comment by lobbin** [comment]
Hi,

No, not really. I don’t mind giving the npm-tvdb name to the other guys, perhaps we could keep it as a new name, tvdb-legacy or something?


regards,
Robin

**Comment by logomaster256** [comment]
I agree with lobbin. If we are going to drop it, then `tvdb-legacy` sounds good but if we aren't then we could switch names with them and have `node-tvdb`. I think we should drop it since their module seems to have everything, but in case they don't have something useful that we have, we could PR it.

**Comment by edwellbrook** [comment]
Hey all. If you find anything you need/want missing from https://github.com/edwellbrook/node-tvdb, please do let me know or submit a PR!

My only issue with swapping names would be people pulling the wrong code with their existing dependencies. Is there even a nice way to go about this that avoids that issue?

**Comment by enyo** [comment]
Hey @edwellbrook Sorry for not doing this earlier.

How about a grace period? I remove my library and put up a note, and then we wait a month, and you put your stuff up?

What do you think?

**Comment by enyo** [comment]
I added you as a collaborator on `npmjs.com` @edwellbrook . I trust that you'll do the migration in an appropriate manner.

**Comment by edwellbrook** [comment]
Sounds good to me. Thanks for this! Want me to keep you updated on how changing things goes or are you okay with me just going ahead with things? :)

**Comment by enyo** [comment]
@edwellbrook would be great if you would post updates here: #23
(just so others can also follow)

**Pull request closed without merging**
